name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
  commit_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Compile C/C++ code
      run: |
        gcc -o output/executable src/*.c src/*.cpp  # Adjust the path if needed
        g++ -o output/executable src/*.cpp  # For C++ files

    - name: Package the executable
      run: zip -r output/CPUConfirm.zip output/executable

    - name: Upload Release Asset
      uses: actions/upload-artifact@v3
      with:
        name: CPUConfirm
        path: output/CPUConfirm.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'release')

    steps:
    - name: Create a Release
      uses: actions/create-release@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: CPUConfirm Release
        draft: false
        prerelease: false
        generate_release_notes: true

    - name: Upload to Release
      uses: actions/upload-release-asset@v3
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: output/CPUConfirm.zip
        asset_name: CPUConfirm.zip
        asset_content_type: application/zip
